### ISSUE TITLE
Feature Request: URI friendly Web API handlers

### ISSUE THREAD

**Issue by zYg-sys** [edwig/Marlin#18]
On the server side, I think Marlin is good at implementing Web APIs.

When adding SiteHandlers, maybe we can take some resource patterns into consideration.

Something like this:
```cpp
    SiteHandler *handler = new UserListHandler();
    site->SetHandler(HTTPCommand::http_get, CString("user"), handler);
    handler = new UserAddHandler();
    site->SetHandler(HTTPCommand::http_post, CString("user"), handler);
    handler = new UserEditHandler();
    site->SetHandler(HTTPCommand::http_put, CString("user/{id}"), handler);
```

When handling the request, we pick the corresponding handler via METHOD and resource pattern.

I think that means a lot of work to do, what do you think?

**Comment by edwig** [comment]
That is a VERY good idea. (And not a lot of work as well). In fact in my production servers 
(in the commercial applications that use the Marlin framework) I have implemented just that.
The handlers there (e.g. the GET) decode a combination of "<tenant>/<database>/<user>" and then accordingly find a session object that was registrated for that user.

But the handler could decode the absolute path element of the URI (here "user" and "user" / id) before calling the general "HandleMessage"
The URI can be parsed to e.g. a vector of strings.

Question:
Are you not implying that there could be multiple handlers per METHOD per uri, as in:

```
   SiteHandler *handler1 = new UserListHandler();
   SiteHandler* handler2 = new GroupListHandler();
   site->SetHandler(HTTPCommand::http_get, CString("user"), handler1);
   site->SetHandler(HTTPCommand::http_get, CString("group"), handler2);
```
??

**Comment by zYg-sys** [comment]
No, a pair of METHOD and resource prefix defines one handler only.

I want to implement API using the generic handler in the beginning,
but it'll be an elegant, instinctive way if Marlin has some builtin mechanism to support Web API development.

Maybe we can call it the Marlin's routing engine:-)

**Comment by zYg-sys** [comment]
let every SiteHandler provides a regexp?
site can use it to pick handler,
and handler itself use it to parse request.

**Comment by edwig** [comment]
OK, Here is a design idea:

1) The FindHTTPSite() from the server finds the longest matching HTTPSite or subsite from an URI. This is done via the 'longest-match' algorithm by scanning backwards through the URL
2) Routing is only handy if the site handler receives by some means a parameter from the part NOT in the matched URI. E.g. if the "user" site receives the "{id}" so that it does not have to parse it for itself
3) Routing information could be stored by the "FindHTTPSite()" method and discarded on a non-match.
4) Routing information can be stored in the HTTPMessage and retreived afterwards in parts as in a "GetRoute(int index)" method. It should be read only of course.
5) Routing information should be propagated to at least the SOAPMessage and maby to the JSONMessage in order to support those frameworks.
6) Handlers for sites and sub-sites alike would receive the overflow of the URI in the from of routing parameters, which the can re-use for their own purpose.
7) Parsing route information in this way is time linear. No regular expression matching needed (which is non-linear)
8) Routing than can be enhanced later to register multiple handlers on the same site or subsite. Multiple handlers are now executed on a stack like manner. Routing could decide (non-stack-like) which handler to pick. This is not in conflict with handlers on sub-sites under the site.

Would this be sufficient in your eyes?

**Comment by edwig** [comment]
Will implement this right after the service framework is done.

**Comment by zYg-sys** [comment]
Nice.
Thanks.
can't wait to use it.
